# https://ap-con.cim4.eu/PowerSchedule-Complex/2.5#DCTieCorridor-powerSchedule
# DCTieCorridor-powerSchedule
# The schedule for the DCTieCorridor is given by its SchedulingArea. Either the schedule of DCTieCorridor or the DCPole is provided.

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


        SELECT DISTINCT $this
        WHERE {
            FILTER EXISTS {
                ?powerSchedule rdf:type nc:PowerSchedule .
            }
			
			BIND (
                EXISTS {
                    $this
                        nc:DCTieCorridor.SchedulingArea
                        ?schedulingArea .
        
                    ?powerSchedule
                        nc:PowerSchedule.SchedulingArea
                        ?schedulingArea .
                }
                AS ?hasSchedulingAreaSchedule
            )
        
            BIND (
                EXISTS {
                    ?dcPole
                        nc:DCPole.DCTieCorridor
                        $this .
        
                    ?powerSchedule
                        nc:PowerSchedule.DCPole
                        ?dcPole .
                }
                AS ?hasDCPoleSchedule
            )
        
            FILTER (
                ?hasSchedulingAreaSchedule="true"^^xsd:boolean
                &&
                ?hasDCPoleSchedule="true"^^xsd:boolean
            )
        }
    