# https://ap-con.cim4.eu/StateInstructionSchedule-Complex/2.5#PowerShiftKeySchedule-associations
# PowerShiftKeySchedule-associations
# PowerShiftKeySchedule shall include one and only one association to ScheduleResource, PowerElectronicUnit, GeneratingUnit, DCPole, EnergyResourceGroupCapacity, EquivalentInjection, EnergyConsumer, EnergySource, ExternalNetworkInjection, SchedulingArea, DCEquivalentInjection, EnergyBlockOrder and HydroPump.

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


      SELECT  $this  
      WHERE {  
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.ScheduleResource ?sr} AS ?vSR).  
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.PowerElectronicUnit ?peu} AS ?vPEU).
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.GeneratingUnit ?gu} AS ?vGU).
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.DCPole ?dcp} AS ?vDCP).
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.EnergyResourceGroupCapacity ?eg} AS ?vEG).
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.EquivalentInjection ?ei} AS ?vEI).
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.EnergyConsumer ?ec} AS ?vEC).
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.EnergySource ?es} AS ?vES).
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.ExternalNetworkInjection ?eni} AS ?vENI).
    BIND(EXISTS{$this nc:PowerShiftKeySchedule.HydroPump ?hp} AS ?vHP).
	
	BIND(EXISTS{$this nc:PowerShiftKeySchedule.SchedulingArea ?sa} AS ?vSA).
	BIND(EXISTS{$this nc:PowerShiftKeySchedule.DCEquivalentInjection ?dcei} AS ?vDCEI).
	BIND(EXISTS{$this nc:PowerShiftKeySchedule.EnergyBlockOrder ?ebo} AS ?vEBO).
        FILTER (
      (?vSR="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
      (?vPEU="true"^^xsd:boolean && (?vSR="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
      (?vGU="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
      (?vDCP="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
      (?vEG="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
      (?vEI="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
      (?vEC="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
      (?vES="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
      (?vENI="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) || 
	  (?vSA="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean)) ||
	  (?vDCEI="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean)) ||
	  (?vEBO="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vHP="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean ||  ?vENI="true"^^xsd:boolean)) ||
      (?vHP="true"^^xsd:boolean && (?vPEU="true"^^xsd:boolean || ?vGU="true"^^xsd:boolean || ?vDCP="true"^^xsd:boolean || ?vEG="true"^^xsd:boolean || ?vEI="true"^^xsd:boolean || ?vEC="true"^^xsd:boolean || ?vES="true"^^xsd:boolean || ?vENI="true"^^xsd:boolean || ?vSR="true"^^xsd:boolean || ?vSA="true"^^xsd:boolean || ?vDCEI="true"^^xsd:boolean || ?vEBO="true"^^xsd:boolean))
    ).
      }